apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: kpng
  name: kpng
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kpng
  template:
    metadata:
      labels:
        app: kpng
    spec:
      containers:
      - args:
        - kube
        - --kubeconfig=/var/lib/kpng/kubeconfig.conf
        - --exportMetrics=0.0.0.0:9099
        - to-local
        - to-ipvsfullstate
        - --v=4
        env:
        - name: GOLANG_PROTOBUF_REGISTRATION_CONFLICT
          value: warn
        image: gcr.io/k8s-staging-win-svc-proxy/kpng:latest
        imagePullPolicy: IfNotPresent
        name: kpng-win
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /k8s
          name: empty
          readOnly: true
#        - mountPath: /var/lib/kpng
#          name: kpng-config
      hostNetwork: true
      securityContext: {}
      nodeSelector:
        kubernetes.io/os: windows
      #      serviceAccount: kpng
#      serviceAccountName: kpng
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - emptyDir: {}
        name: empty
#      - configMap:
#          defaultMode: 420
#          name: kpng
#        name: kpng-config
