---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: windows-server-iis
spec:
    selector:
        matchLabels:
            app: windows-server-iis
    replicas: 1
    template:
        metadata:
            labels:
                app: windows-server-iis
        spec:
          tolerations:
          - effect: NoSchedule
            key: os
            operator: Equal
            value: windows
          - effect: NoSchedule
            key: os
            operator: Equal
            value: Windows    
          containers:
          - name: windows-server-iis
            image: mcr.microsoft.com/windows/servercore/iis
            imagePullPolicy: IfNotPresent
            command:
            - powershell.exe
            - -command
            - "echo '<html><body><br/><br/><marquee><H1>Hello EKS!!!<H1><marquee></body><html>' > C:\\inetpub\\wwwroot\\default.html; C:\\ServiceMonitor.exe 'w3svc'; "
          nodeSelector:
            kubernetes.io/os: windows
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
spec:
    selector:
        matchLabels:
            app: nginx
    replicas: 1
    template:
        metadata:
            labels:
                app: nginx
        spec:
          tolerations:
          - effect: NoSchedule
            key: os
            operator: Equal
            value: windows
          - effect: NoSchedule
            key: os
            operator: Equal
            value: Windows
          containers:
          - name: nginx
            image: nginx:1.7.9
            securityContext:
              privileged: true
          nodeSelector:
            beta.kubernetes.io/os: linux
